services:
  server:
    container_name: dotchat-server
    image: ghcr.io/luoda2023/luoda-server:latest
    entrypoint: /entrypoint.sh
    environment:
      - HBBS_PORT=23116
      - HBBR_PORT=23117
      - API_ADDR=0.0.0.0:23114
      - RELAY=dotchat.dicad.cn:23117
    volumes:
      - ./docker/entrypoint.sh:/entrypoint.sh:ro
      - ./data:/data
    network_mode: "host"
    restart: unless-stopped
