services:
  hbbs:
    container_name: LUODA-hbbs
    image: ghcr.io/luoda2023/luoda-server:latest
    command: hbbs -r rev.dicad.cn
    volumes:
      - ./data/id_ed25519:/root/id_ed25519:ro
      - ./data/id_ed25519.pub:/root/id_ed25519.pub:ro
      - ./data:/root
    network_mode: "host"
    restart: unless-stopped

  hbbr:
    container_name: LUODA-hbbr
    image: ghcr.io/luoda2023/luoda-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: unless-stopped