services:
  luoda-api:
    image: luoda2023/luoda-api
    container_name: dotchat-api
    environment:
      - TZ=Asia/Shanghai
      - LUODA_API_LUODA_ID_SERVER=dotchat.dicad.cn:23116
      - LUODA_API_LUODA_RELAY_SERVER=dotchat.dicad.cn:23117
      - LUODA_API_LUODA_API_SERVER=http://127.0.0.1:23114
      - LUODA_API_LUODA_KEY=<DOTCHAT_PUB_KEY>
    ports:
      - 23114:23114
    volumes:
      - ./data/LUODA/api:/app/data
      - ./conf:/app/conf
      - ./resources:/app/resources
    restart: unless-stopped
